#!/usr/bin/env bash
# Write the manual page and the shell completion scripts that the .deb and
# .rpm install (packaging/nfpm.yaml), generated by a Linux neoscad binary
# (`neoscad generate`, crates/cli/src/generate.rs):
#
#   scripts/release/man-completions.sh NEOSCAD DEST
#
# DEST/neoscad.1.gz, and DEST/completions/ with neoscad.bash, _neoscad
# (zsh) and neoscad.fish. `gzip -n` leaves out the name and time stamp,
# so the same binary gives the same bytes and a rebuilt package does not
# differ from the first. The binary must run here: the release workflow
# uses its x86_64 build for both architectures' packages (the output
# does not depend on the architecture), and linux-packages.sh runs this
# inside a container.
set -euo pipefail

[[ $# -eq 2 ]] || { sed -n '5p' "$0" >&2; exit 2; }
bin=$1
dest=$2

mkdir -p "$dest/completions"
"$bin" generate man | gzip -9n >"$dest/neoscad.1.gz"
"$bin" generate completions bash >"$dest/completions/neoscad.bash"
"$bin" generate completions zsh >"$dest/completions/_neoscad"
"$bin" generate completions fish >"$dest/completions/neoscad.fish"
