#!/usr/bin/env python3
"""Stand-ins for what the XAML compiler generates, so the WinUI app's C#
type-checks off Windows (scripts/windows/docker-typecheck.sh).

For each XAML file given (a Window or Application with x:Class), writes a
partial class with:

  - a field for every x:Name, typed as its element (WinUI's
    Microsoft.UI.Xaml.Controls, or the namespace a prefix maps to);
  - an empty InitializeComponent();
  - a method that subscribes every event handler the XAML names
    (Click="OnSave") to a fresh element of its type, so a handler whose
    name or signature does not fit its event fails to compile, as it
    would in the XAML compiler.

    xaml-standins.py OUT.cs FILE.xaml...
"""

import sys
import xml.etree.ElementTree as ET

XAML = "http://schemas.microsoft.com/winfx/2006/xaml"
PRESENTATION = "http://schemas.microsoft.com/winfx/2006/xaml/presentation"

# Elements outside Microsoft.UI.Xaml.Controls that the app's XAML uses.
NAMESPACES = {
    "KeyboardAccelerator": "Microsoft.UI.Xaml.Input",
    "MicaBackdrop": "Microsoft.UI.Xaml.Media",
    "RowDefinition": "Microsoft.UI.Xaml.Controls",
    "Window": "Microsoft.UI.Xaml",
    "Application": "Microsoft.UI.Xaml",
}
# An attribute whose value names a handler (On...) is an event.
HANDLER_PREFIX = "On"
# Fields the XAML loader assigns look unassigned to the compiler.
HEADER = [
    "// Generated by scripts/windows/xaml-standins.py; not checked in.",
    "#nullable disable",
    "#pragma warning disable CS0649 // assigned by the XAML loader on Windows",
    "",
]


def type_of(tag):
    ns, _, local = tag[1:].partition("}") if tag.startswith("{") else ("", "", tag)
    if ns not in (PRESENTATION, ""):
        return None
    if "." in local:  # a property element (Grid.RowDefinitions)
        return None
    return f"global::{NAMESPACES.get(local, 'Microsoft.UI.Xaml.Controls')}.{local}"


def main():
    out, files = sys.argv[1], sys.argv[2:]
    for path in files:
        root = ET.parse(path).getroot()
        cls = root.get(f"{{{XAML}}}Class")
        ns, _, name = cls.rpartition(".")
        base = type_of(root.tag)
        fields, wiring = [], []
        for e in root.iter():
            t = type_of(e.tag)
            if t is None:
                continue
            x_name = e.get(f"{{{XAML}}}Name")
            if x_name and e is not root:
                fields.append(f"    internal {t} {x_name};")
            for attr, value in e.attrib.items():
                if attr.startswith("{") or not value.startswith(HANDLER_PREFIX) or "." in attr:
                    continue
                if not value[len(HANDLER_PREFIX):][:1].isupper():
                    continue
                wiring.append(f"        {{ {t} e = null; e.{attr} += {value}; }}")
        parts = HEADER + [
            f"namespace {ns};",
            "",
            f"partial class {name} : {base}",
            "{",
            *fields,
            "    void InitializeComponent() { }",
            "    void StandInWiring()",
            "    {",
            *wiring,
            "    }",
            "}",
            "",
        ]
        # One namespace per file is all C# allows with file-scoped
        # namespaces, so each class goes in its own file.
        with open(out.replace(".cs", f".{name}.cs"), "w") as f:
            f.write("\n".join(parts))


if __name__ == "__main__":
    main()
