//! POV-Ray scene export (`src/io/export_pov.cc`).
//!
//! One `polygon` per mesh face (faces are not triangulated), a 3x3x3 grid
//! of dim lights around the bounding box, and a camera. Numbers print as
//! C++ streams print them (`%g`, six significant digits).

use crate::Color;
use crate::mesh::MeshRef;
use crate::text::fmt_g;

/// The view the scene's camera takes (`ExportInfo::camera`).
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct PovCamera {
    /// `$vpt`.
    pub translation: [f64; 3],
    /// `$vpr`: pitch, yaw, roll.
    pub rotation: [f64; 3],
    /// `viewer_distance` (`$vpd`).
    pub distance: f64,
    /// `fov` (`$vpf`).
    pub fov: f64,
}

/// What the scene records besides the mesh.
#[derive(Debug, Clone)]
pub struct PovOptions<'a> {
    /// The input file's name, for the header comment.
    pub title: &'a str,
    /// The colour scheme's face colour, for faces without a colour.
    pub default_color: Color,
    /// The command line always has a camera; without one the scene gets
    /// OpenSCAD's fallback camera looking at the bounding box.
    pub camera: Option<PovCamera>,
}

/// `export_pov` for a mesh (OpenSCAD's `getGeometryAsPolySet` of the
/// result). The lights and the fallback camera use the mesh's bounding
/// box, which is the geometry's.
pub fn write(mesh: MeshRef<'_>, opts: &PovOptions<'_>) -> Vec<u8> {
    let g = fmt_g;
    let mut out = String::with_capacity(1024 + mesh.faces.len() * 256);
    out.push_str("// Generated by OpenSCAD (https://www.openscad.org/)\n");
    out.push_str(&format!("// Source file: {}\n\n", opts.title));
    out.push_str("// Camera settings are at the bottom of this script\n\n");
    out.push_str("#version 3.7;\n");
    out.push_str("global_settings { assumed_gamma 1.0 }\n");
    out.push_str("#declare MATERIAL=finish { specular 0.5 roughness 0.001 reflection{0 0.63 fresnel} ambient 0 diffuse 0.6 conserve_energy }\n");
    out.push_str("#declare MATERIAL_INT=interior{ior 1.32}\n");

    let has_color = !mesh.color_indices.is_empty();
    let point = |v: [f64; 3]| format!("<{}, {}, {}>", g(v[0]), g(v[1]), g(v[2]));
    for (fi, face) in mesh.faces.iter().enumerate() {
        out.push_str(&format!("polygon {{ {}, \n", face.len() + 1));
        let pts: Vec<String> = face
            .iter()
            .map(|&i| point(mesh.vertices[i as usize]))
            .collect();
        out.push_str(&pts.join(", "));
        if let Some(&first) = face.first() {
            out.push_str(&format!(", {}", point(mesh.vertices[first as usize])));
        }
        // The components are `float`s; the filter is `float f = 1.0 - a`.
        let [mut r, mut gr, mut b, _] = opts.default_color.0;
        let mut f = 0.0f32;
        if has_color && let Some(c) = mesh.face_color(fi) {
            [r, gr, b] = [c.0[0], c.0[1], c.0[2]];
            f = (1.0 - f64::from(c.0[3])) as f32;
        }
        out.push_str(&format!(
            "\ntexture {{ pigment {{ color rgbf <{}, {}, {}, {}> }} }}\n",
            g(f64::from(r)),
            g(f64::from(gr)),
            g(f64::from(b)),
            g(f64::from(f))
        ));
        out.push_str("finish { MATERIAL } interior { MATERIAL_INT }\n");
        out.push_str("}\n");
    }

    let (min, max) = bounds(mesh.vertices);
    let d = [max[0] - min[0], max[1] - min[1], max[2] - min[2]];
    let center = [
        (min[0] + max[0]) / 2.0,
        (min[1] + max[1]) / 2.0,
        (min[2] + max[2]) / 2.0,
    ];
    const MOVE_AWAY: f64 = 2.0;
    let axis = |k: usize| {
        [
            min[k] - d[k] * MOVE_AWAY,
            center[k],
            max[k] + d[k] * MOVE_AWAY,
        ]
    };
    // `constexpr float brightness = 0.2`, printed as a float.
    let brightness = g(f64::from(0.2f32));
    for x in axis(0) {
        for y in axis(1) {
            for z in axis(2) {
                out.push_str(&format!(
                    "light_source {{ <{}, {}, {}> color rgb <{brightness}, {brightness}, {brightness}> }}\n",
                    g(x),
                    g(y),
                    g(z)
                ));
            }
        }
    }

    match &opts.camera {
        Some(c) => {
            out.push_str(&format!(
                "camera {{ look_at <0, 0, 0>\n location <0, 0, {}>\n angle {} up <0, 1, 0> right <1, 0, 0> sky <0, 1, 0> right -x*image_width/image_height\ntranslate <{}, {}, {}>\nrotate <{}, {} + clock * 3, {} + clock>\n}}\n",
                g(c.distance),
                g(c.fov),
                g(c.translation[0]),
                g(c.translation[1]),
                g(c.translation[2]),
                g(c.rotation[0]),
                g(c.rotation[1]),
                g(c.rotation[2]),
            ));
        }
        None => {
            out.push_str(&format!(
                "camera {{ look_at <{}, {}, {}> location <{}, {}, {}> up <0, 0, 1> right <1, 0, 0> sky <0, 0, 1> rotate <-55, clock * 3, clock + 25> right x*image_width/image_height }}\n",
                g(center[0]),
                g(center[1]),
                g(center[2]),
                g(min[0] + d[0] * MOVE_AWAY),
                g(min[1] - d[1] * MOVE_AWAY),
                g(min[2] + d[2] * MOVE_AWAY),
            ));
        }
    }
    out.push_str("#include \"rad_def.inc\"\n");
    out.push_str("global_settings { photons { count 20000 autostop 0 jitter .4 } radiosity { Rad_Settings(Radiosity_Normal, off, off) } }\n");
    out.into_bytes()
}

/// The mesh's bounding box; all zeros for an empty mesh (the command line
/// refuses to export one).
fn bounds(vertices: &[[f64; 3]]) -> ([f64; 3], [f64; 3]) {
    let Some(first) = vertices.first() else {
        return ([0.0; 3], [0.0; 3]);
    };
    let (mut min, mut max) = (*first, *first);
    for v in vertices {
        for k in 0..3 {
            min[k] = min[k].min(v[k]);
            max[k] = max[k].max(v[k]);
        }
    }
    (min, max)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::Mesh;

    /// `cube(1);` as the nightly's `PolySet` holds it (the OFF export's
    /// vertex and face order).
    fn cube() -> Mesh {
        Mesh {
            vertices: vec![
                [0.0, 0.0, 0.0],
                [1.0, 0.0, 0.0],
                [0.0, 1.0, 0.0],
                [1.0, 1.0, 0.0],
                [0.0, 0.0, 1.0],
                [1.0, 0.0, 1.0],
                [0.0, 1.0, 1.0],
                [1.0, 1.0, 1.0],
            ],
            faces: vec![
                vec![4, 5, 7, 6],
                vec![2, 3, 1, 0],
                vec![0, 1, 5, 4],
                vec![1, 3, 7, 5],
                vec![3, 2, 6, 7],
                vec![2, 0, 4, 6],
            ],
            colors: vec![],
            color_indices: vec![],
        }
    }

    #[test]
    fn cube_matches_the_nightly() {
        let m = cube();
        let text = String::from_utf8(write(
            m.as_ref(),
            &PovOptions {
                title: "c.scad",
                default_color: Color::from_u8(0xf9, 0xd7, 0x2c),
                camera: Some(PovCamera {
                    translation: [0.0; 3],
                    rotation: [55.0, 0.0, 25.0],
                    distance: 140.0,
                    fov: 22.5,
                }),
            },
        ))
        .unwrap();
        // `openscad -o c.pov` on `cube(1);`, 2026.09.23 nightly: the head,
        // the first polygon, the first light and the whole tail.
        assert!(text.starts_with("// Generated by OpenSCAD (https://www.openscad.org/)\n// Source file: c.scad\n\n// Camera settings are at the bottom of this script\n\n#version 3.7;\nglobal_settings { assumed_gamma 1.0 }\n#declare MATERIAL=finish { specular 0.5 roughness 0.001 reflection{0 0.63 fresnel} ambient 0 diffuse 0.6 conserve_energy }\n#declare MATERIAL_INT=interior{ior 1.32}\npolygon { 5, \n<0, 0, 1>, <1, 0, 1>, <1, 1, 1>, <0, 1, 1>, <0, 0, 1>\ntexture { pigment { color rgbf <0.976471, 0.843137, 0.172549, 0> } }\nfinish { MATERIAL } interior { MATERIAL_INT }\n}\npolygon { 5, \n<0, 1, 0>, "));
        assert!(text.contains("}\nlight_source { <-2, -2, -2> color rgb <0.2, 0.2, 0.2> }\nlight_source { <-2, -2, 0.5> color rgb <0.2, 0.2, 0.2> }\n"));
        assert!(text.ends_with("light_source { <3, 3, 3> color rgb <0.2, 0.2, 0.2> }\ncamera { look_at <0, 0, 0>\n location <0, 0, 140>\n angle 22.5 up <0, 1, 0> right <1, 0, 0> sky <0, 1, 0> right -x*image_width/image_height\ntranslate <0, 0, 0>\nrotate <55, 0 + clock * 3, 25 + clock>\n}\n#include \"rad_def.inc\"\nglobal_settings { photons { count 20000 autostop 0 jitter .4 } radiosity { Rad_Settings(Radiosity_Normal, off, off) } }\n"));
        assert_eq!(text.matches("light_source").count(), 27);
    }

    #[test]
    fn face_colours_and_alpha_as_a_filter() {
        let mut m = cube();
        m.colors = vec![Color([0.0, 0.0, 1.0, 0.5]), Color([1.0, 0.0, 0.0, 1.0])];
        m.color_indices = vec![0, 1, -1, 0, 0, 0];
        let text = String::from_utf8(write(
            m.as_ref(),
            &PovOptions {
                title: "col.scad",
                default_color: Color::from_u8(0xf9, 0xd7, 0x2c),
                camera: None,
            },
        ))
        .unwrap();
        assert!(text.contains("color rgbf <0, 0, 1, 0.5>"));
        assert!(text.contains("color rgbf <1, 0, 0, 0>"));
        assert!(text.contains("color rgbf <0.976471, 0.843137, 0.172549, 0>"));
        assert!(text.contains("camera { look_at <0.5, 0.5, 0.5> location <2, -2, 2> up <0, 0, 1>"));
    }
}
